### ISSUE TITLE
safe multi-agent

### ISSUE THREAD

**Issue by QingyuanWuNothing** [liuzuxin/DSRL#2]
It is excellent work! Whether DSRL support multi-agent settings (e.g., Safe Multi-Agent in safety-gymnasium) in the future?

**Comment by weakenleg** [comment]
I have the same question, and I hope future work will consider it.

**Comment by liuzuxin** [comment]
Hi @QingyuanWuNothing @weakenleg , thanks for your interest in our work! My collaborators and I are discussing the best ways of integrating MARL settings with DSRL, but unfortunately, they won't come out in a short timeframe because of the many challenges we might face. BTW you are always welcome to contribute your datasets and environments to this repo.
