### ISSUE TITLE
Unbounded actions in datasets

### ISSUE THREAD

**Issue by qianlin04** [liuzuxin/DSRL#5]
Hi,

I find that action values in some datasets (e.g., BallCircle, CarCircle, DroneCircle) are out of bounds of environments (i.e., [-1, 1]). However, the actions in D4RL are bounded, and when using train_trpol_expert.py to collect new data, we also get bounded actions.

So I want to know if everything is okay. Should I directly clip the actions when I use the datasets?

**Comment by zgong11** [comment]
> Hi,
> 
> I find that action values in some datasets (e.g., BallCircle, CarCircle, DroneCircle) are out of bounds of environments (i.e., [-1, 1]). However, the actions in D4RL are bounded, and when using train_trpol_expert.py to collect new data, we also get bounded actions.
> 
> So I want to know if everything is okay. Should I directly clip the actions when I use the datasets?

@liuzuxin @Ja4822 @HenryLHH @yihangyao Same issues here.  May I know how do you resolve it? @qianlin04

**Comment by liuzuxin** [comment]
Hi @zgong11 and @qianlin04 , sorry for the oversight. For some BulletSafetyGym environment, there are indeed such issues. You can either clip the actions in the datasets or just ignore them, because the BulletSafetyGym environment will clip the actions to the correct range [-1, 1], as shown [here](https://github.com/liuzuxin/Bullet-Safety-Gym/blob/6f9f480a096b9fc2b9991e994fdea9ef9fb776bb/bullet_safety_gym/envs/bases.py#L620-L625).

**Comment by qianlin04** [comment]
Hi @liuzuxin , thanks for your reply. Actually, I'm a bit confused about the difference between the publicly available datasets and the ones generated by code, but there don't seem to be any unexpected issues when I directly use the clipped actions in my project.
